# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(693, 411)
        self.btnSolve = QtWidgets.QPushButton(Dialog)
        self.btnSolve.setGeometry(QtCore.QRect(440, 360, 91, 31))
        self.btnSolve.setObjectName("btnSolve")
        self.btnClear = QtWidgets.QPushButton(Dialog)
        self.btnClear.setGeometry(QtCore.QRect(560, 360, 91, 31))
        self.btnClear.setObjectName("btnClear")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_1 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_1.setGeometry(QtCore.QRect(30, 20, 31, 31))
        self.textEdit_1.setFont(font)
        self.textEdit_1.setObjectName("textEdit_1")

        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(70, 20, 31, 31))
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")

        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(110, 20, 31, 31))
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")

        self.textEdit_4 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_4.setGeometry(QtCore.QRect(160, 20, 31, 31))
        self.textEdit_4.setFont(font)
        self.textEdit_4.setObjectName("textEdit_4")

        self.textEdit_5 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_5.setGeometry(QtCore.QRect(200, 20, 31, 31))
        self.textEdit_5.setFont(font)
        self.textEdit_5.setObjectName("textEdit_5")

        self.textEdit_6 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_6.setGeometry(QtCore.QRect(240, 20, 31, 31))
        self.textEdit_6.setFont(font)
        self.textEdit_6.setObjectName("textEdit_6")

        self.textEdit_7 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_7.setGeometry(QtCore.QRect(290, 20, 31, 31))
        self.textEdit_7.setFont(font)
        self.textEdit_7.setObjectName("textEdit_7")

        self.textEdit_8 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_8.setGeometry(QtCore.QRect(330, 20, 31, 31))
        self.textEdit_8.setFont(font)
        self.textEdit_8.setObjectName("textEdit_8")

        self.textEdit_9 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_9.setGeometry(QtCore.QRect(370, 20, 31, 31))
        self.textEdit_9.setFont(font)
        self.textEdit_9.setObjectName("textEdit_9")

        self.textEdit_10 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_10.setGeometry(QtCore.QRect(30, 60, 31, 31))
        self.textEdit_10.setFont(font)
        self.textEdit_10.setObjectName("textEdit_10")

        self.textEdit_11 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_11.setGeometry(QtCore.QRect(70, 60, 31, 31))
        self.textEdit_11.setFont(font)
        self.textEdit_11.setObjectName("textEdit_11")

        self.textEdit_12 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_12.setGeometry(QtCore.QRect(110, 60, 31, 31))
        self.textEdit_12.setFont(font)
        self.textEdit_12.setObjectName("textEdit_12")

        self.textEdit_13 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_13.setGeometry(QtCore.QRect(160, 60, 31, 31))
        self.textEdit_13.setFont(font)
        self.textEdit_13.setObjectName("textEdit_13")

        self.textEdit_14 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_14.setGeometry(QtCore.QRect(200, 60, 31, 31))
        self.textEdit_14.setFont(font)
        self.textEdit_14.setObjectName("textEdit_14")

        self.textEdit_15 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_15.setGeometry(QtCore.QRect(240, 60, 31, 31))
        self.textEdit_15.setFont(font)
        self.textEdit_15.setObjectName("textEdit_15")

        self.textEdit_16 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_16.setGeometry(QtCore.QRect(290, 60, 31, 31))
        self.textEdit_16.setFont(font)
        self.textEdit_16.setObjectName("textEdit_16")

        self.textEdit_17 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_17.setGeometry(QtCore.QRect(330, 60, 31, 31))
        self.textEdit_17.setFont(font)
        self.textEdit_17.setObjectName("textEdit_17")

        self.textEdit_18 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_18.setGeometry(QtCore.QRect(370, 60, 31, 31))
        self.textEdit_18.setFont(font)
        self.textEdit_18.setObjectName("textEdit_18")

        self.textEdit_19 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_19.setGeometry(QtCore.QRect(30, 100, 31, 31))
        self.textEdit_19.setFont(font)
        self.textEdit_19.setObjectName("textEdit_19")

        self.textEdit_20 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_20.setGeometry(QtCore.QRect(70, 100, 31, 31))
        self.textEdit_20.setFont(font)
        self.textEdit_20.setObjectName("textEdit_20")

        self.textEdit_21 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_21.setGeometry(QtCore.QRect(110, 100, 31, 31))
        self.textEdit_21.setFont(font)
        self.textEdit_21.setObjectName("textEdit_21")

        self.textEdit_22 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_22.setGeometry(QtCore.QRect(160, 100, 31, 31))
        self.textEdit_22.setFont(font)
        self.textEdit_22.setObjectName("textEdit_22")

        self.textEdit_23 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_23.setGeometry(QtCore.QRect(200, 100, 31, 31))
        self.textEdit_23.setFont(font)
        self.textEdit_23.setObjectName("textEdit_23")

        self.textEdit_24 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_24.setGeometry(QtCore.QRect(240, 100, 31, 31))
        self.textEdit_24.setFont(font)
        self.textEdit_24.setObjectName("textEdit_24")

        self.textEdit_25 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_25.setGeometry(QtCore.QRect(290, 100, 31, 31))
        self.textEdit_25.setFont(font)
        self.textEdit_25.setObjectName("textEdit_25")

        self.textEdit_26 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_26.setGeometry(QtCore.QRect(330, 100, 31, 31))
        self.textEdit_26.setFont(font)
        self.textEdit_26.setObjectName("textEdit_26")

        self.textEdit_27 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_27.setGeometry(QtCore.QRect(370, 100, 31, 31))
        self.textEdit_27.setFont(font)
        self.textEdit_27.setObjectName("textEdit_27")

        self.textEdit_28 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_28.setGeometry(QtCore.QRect(30, 150, 31, 31))
        self.textEdit_28.setFont(font)
        self.textEdit_28.setObjectName("textEdit_28")

        self.textEdit_29 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_29.setGeometry(QtCore.QRect(70, 150, 31, 31))
        self.textEdit_29.setFont(font)
        self.textEdit_29.setObjectName("textEdit_29")

        self.textEdit_30 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_30.setGeometry(QtCore.QRect(110, 150, 31, 31))
        self.textEdit_30.setFont(font)
        self.textEdit_30.setObjectName("textEdit_30")

        self.textEdit_31 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_31.setGeometry(QtCore.QRect(160, 150, 31, 31))
        self.textEdit_31.setFont(font)
        self.textEdit_31.setObjectName("textEdit_31")

        self.textEdit_32 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_32.setGeometry(QtCore.QRect(200, 150, 31, 31))
        self.textEdit_32.setFont(font)
        self.textEdit_32.setObjectName("textEdit_32")

        self.textEdit_33 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_33.setGeometry(QtCore.QRect(240, 150, 31, 31))
        self.textEdit_33.setFont(font)
        self.textEdit_33.setObjectName("textEdit_33")

        self.textEdit_34 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_34.setGeometry(QtCore.QRect(290, 150, 31, 31))
        self.textEdit_34.setFont(font)
        self.textEdit_34.setObjectName("textEdit_34")

        self.textEdit_35 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_35.setGeometry(QtCore.QRect(330, 150, 31, 31))
        self.textEdit_35.setFont(font)
        self.textEdit_35.setObjectName("textEdit_35")

        self.textEdit_36 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_36.setGeometry(QtCore.QRect(370, 150, 31, 31))
        self.textEdit_36.setFont(font)
        self.textEdit_36.setObjectName("textEdit_36")

        self.textEdit_37 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_37.setGeometry(QtCore.QRect(30, 190, 31, 31))
        self.textEdit_37.setFont(font)
        self.textEdit_37.setObjectName("textEdit_37")

        self.textEdit_38 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_38.setGeometry(QtCore.QRect(70, 190, 31, 31))
        self.textEdit_38.setFont(font)
        self.textEdit_38.setObjectName("textEdit_38")

        self.textEdit_39 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_39.setGeometry(QtCore.QRect(110, 190, 31, 31))
        self.textEdit_39.setFont(font)
        self.textEdit_39.setObjectName("textEdit_39")

        self.textEdit_40 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_40.setGeometry(QtCore.QRect(160, 190, 31, 31))
        self.textEdit_40.setFont(font)
        self.textEdit_40.setObjectName("textEdit_40")

        self.textEdit_41 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_41.setGeometry(QtCore.QRect(200, 190, 31, 31))
        self.textEdit_41.setFont(font)
        self.textEdit_41.setObjectName("textEdit_41")

        self.textEdit_42 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_42.setGeometry(QtCore.QRect(240, 190, 31, 31))
        self.textEdit_42.setFont(font)
        self.textEdit_42.setObjectName("textEdit_42")

        self.textEdit_43 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_43.setGeometry(QtCore.QRect(290, 190, 31, 31))
        self.textEdit_43.setFont(font)
        self.textEdit_43.setObjectName("textEdit_43")

        self.textEdit_44 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_44.setGeometry(QtCore.QRect(330, 190, 31, 31))
        self.textEdit_44.setFont(font)
        self.textEdit_44.setObjectName("textEdit_44")

        self.textEdit_45 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_45.setGeometry(QtCore.QRect(370, 190, 31, 31))
        self.textEdit_45.setFont(font)
        self.textEdit_45.setObjectName("textEdit_45")

        self.textEdit_46 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_46.setGeometry(QtCore.QRect(30, 230, 31, 31))
        self.textEdit_46.setFont(font)
        self.textEdit_46.setObjectName("textEdit_46")

        self.textEdit_47 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_47.setGeometry(QtCore.QRect(70, 230, 31, 31))
        self.textEdit_47.setFont(font)
        self.textEdit_47.setObjectName("textEdit_47")

        self.textEdit_48 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_48.setGeometry(QtCore.QRect(110, 230, 31, 31))
        self.textEdit_48.setFont(font)
        self.textEdit_48.setObjectName("textEdit_48")

        self.textEdit_49 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_49.setGeometry(QtCore.QRect(160, 230, 31, 31))
        self.textEdit_49.setFont(font)
        self.textEdit_49.setObjectName("textEdit_49")

        self.textEdit_50 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_50.setGeometry(QtCore.QRect(200, 230, 31, 31))
        self.textEdit_50.setFont(font)
        self.textEdit_50.setObjectName("textEdit_50")

        self.textEdit_51 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_51.setGeometry(QtCore.QRect(240, 230, 31, 31))
        self.textEdit_51.setFont(font)
        self.textEdit_51.setObjectName("textEdit_51")

        self.textEdit_52 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_52.setGeometry(QtCore.QRect(290, 230, 31, 31))
        self.textEdit_52.setFont(font)
        self.textEdit_52.setObjectName("textEdit_52")

        self.textEdit_53 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_53.setGeometry(QtCore.QRect(330, 230, 31, 31))
        self.textEdit_53.setFont(font)
        self.textEdit_53.setObjectName("textEdit_53")

        self.textEdit_54 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_54.setGeometry(QtCore.QRect(370, 230, 31, 31))
        self.textEdit_54.setFont(font)
        self.textEdit_54.setObjectName("textEdit_54")

        self.textEdit_55 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_55.setGeometry(QtCore.QRect(30, 280, 31, 31))
        self.textEdit_55.setFont(font)
        self.textEdit_55.setObjectName("textEdit_55")

        self.textEdit_56 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_56.setGeometry(QtCore.QRect(70, 280, 31, 31))
        self.textEdit_56.setFont(font)
        self.textEdit_56.setObjectName("textEdit_56")

        self.textEdit_57 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_57.setGeometry(QtCore.QRect(110, 280, 31, 31))
        self.textEdit_57.setFont(font)
        self.textEdit_57.setObjectName("textEdit_57")

        self.textEdit_58 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_58.setGeometry(QtCore.QRect(160, 280, 31, 31))
        self.textEdit_58.setFont(font)
        self.textEdit_58.setObjectName("textEdit_58")

        self.textEdit_59 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_59.setGeometry(QtCore.QRect(200, 280, 31, 31))
        self.textEdit_59.setFont(font)
        self.textEdit_59.setObjectName("textEdit_59")

        self.textEdit_60 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_60.setGeometry(QtCore.QRect(240, 280, 31, 31))
        self.textEdit_60.setFont(font)
        self.textEdit_60.setObjectName("textEdit_60")

        self.textEdit_61 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_61.setGeometry(QtCore.QRect(290, 280, 31, 31))
        self.textEdit_61.setFont(font)
        self.textEdit_61.setObjectName("textEdit_61")

        self.textEdit_62 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_62.setGeometry(QtCore.QRect(330, 280, 31, 31))
        self.textEdit_62.setFont(font)
        self.textEdit_62.setObjectName("textEdit_62")

        self.textEdit_63 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_63.setGeometry(QtCore.QRect(370, 280, 31, 31))
        self.textEdit_63.setFont(font)
        self.textEdit_63.setObjectName("textEdit_63")

        self.textEdit_64 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_64.setGeometry(QtCore.QRect(30, 320, 31, 31))
        self.textEdit_64.setFont(font)
        self.textEdit_64.setObjectName("textEdit_64")

        self.textEdit_65 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_65.setGeometry(QtCore.QRect(70, 320, 31, 31))
        self.textEdit_65.setFont(font)
        self.textEdit_65.setObjectName("textEdit_65")

        self.textEdit_66 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_66.setGeometry(QtCore.QRect(110, 320, 31, 31))
        self.textEdit_66.setFont(font)
        self.textEdit_66.setObjectName("textEdit_66")

        self.textEdit_67 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_67.setGeometry(QtCore.QRect(160, 320, 31, 31))
        self.textEdit_67.setFont(font)
        self.textEdit_67.setObjectName("textEdit_67")

        self.textEdit_68 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_68.setGeometry(QtCore.QRect(200, 320, 31, 31))
        self.textEdit_68.setFont(font)
        self.textEdit_68.setObjectName("textEdit_68")

        self.textEdit_69 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_69.setGeometry(QtCore.QRect(240, 320, 31, 31))
        self.textEdit_69.setFont(font)
        self.textEdit_69.setObjectName("textEdit_69")

        self.textEdit_70 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_70.setGeometry(QtCore.QRect(290, 320, 31, 31))
        self.textEdit_70.setFont(font)
        self.textEdit_70.setObjectName("textEdit_70")

        self.textEdit_71 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_71.setGeometry(QtCore.QRect(330, 320, 31, 31))
        self.textEdit_71.setFont(font)
        self.textEdit_71.setObjectName("textEdit_71")

        self.textEdit_72 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_72.setGeometry(QtCore.QRect(370, 320, 31, 31))
        self.textEdit_72.setFont(font)
        self.textEdit_72.setObjectName("textEdit_72")

        self.textEdit_73 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_73.setGeometry(QtCore.QRect(30, 360, 31, 31))
        self.textEdit_73.setFont(font)
        self.textEdit_73.setObjectName("textEdit_73")

        self.textEdit_74 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_74.setGeometry(QtCore.QRect(70, 360, 31, 31))
        self.textEdit_74.setFont(font)
        self.textEdit_74.setObjectName("textEdit_74")

        self.textEdit_75 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_75.setGeometry(QtCore.QRect(110, 360, 31, 31))
        self.textEdit_75.setFont(font)
        self.textEdit_75.setObjectName("textEdit_75")

        self.textEdit_76 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_76.setGeometry(QtCore.QRect(160, 360, 31, 31))
        self.textEdit_76.setFont(font)
        self.textEdit_76.setObjectName("textEdit_76")

        self.textEdit_77 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_77.setGeometry(QtCore.QRect(200, 360, 31, 31))
        self.textEdit_77.setFont(font)
        self.textEdit_77.setObjectName("textEdit_77")

        self.textEdit_78 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_78.setGeometry(QtCore.QRect(240, 360, 31, 31))
        self.textEdit_78.setFont(font)
        self.textEdit_78.setObjectName("textEdit_78")

        self.textEdit_79 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_79.setGeometry(QtCore.QRect(290, 360, 31, 31))
        self.textEdit_79.setFont(font)
        self.textEdit_79.setObjectName("textEdit_79")

        self.textEdit_80 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_80.setGeometry(QtCore.QRect(330, 360, 31, 31))
        self.textEdit_80.setFont(font)
        self.textEdit_80.setObjectName("textEdit_80")

        self.textEdit_81 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_81.setGeometry(QtCore.QRect(370, 360, 31, 31))
        self.textEdit_81.setFont(font)
        self.textEdit_81.setObjectName("textEdit_81")


        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(30, 130, 371, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(30, 260, 371, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(270, 20, 20, 371))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(140, 20, 20, 371))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(420, 20, 251, 331))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setFont(font)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sudoku solver"))
        self.btnSolve.setText(_translate("Dialog", "Розв’язати"))
        self.btnClear.setText(_translate("Dialog", "Очистити"))
        self.textBrowser.setPlaceholderText(_translate("Dialog", "Всі значення крім 0-9 будуть замінятись на 0"))
        self.textEdit_1.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_2.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_3.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_12.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_10.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_11.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_21.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_19.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_20.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_6.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_15.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_24.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_4.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_13.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_23.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_5.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_22.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_14.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_17.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_26.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_25.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_9.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_18.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_16.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_8.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_27.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_7.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_54.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_33.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_45.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_30.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_42.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_32.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_36.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_44.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_38.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_41.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_51.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_47.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_48.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_53.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_31.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_52.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_35.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_34.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_40.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_28.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_50.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_46.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_39.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_49.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_37.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_43.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_29.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_77.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_57.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_73.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_81.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_64.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_58.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_76.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_66.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_68.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_75.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_63.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_67.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_60.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_62.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_80.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_56.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_74.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_72.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_65.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_55.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_69.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_70.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_78.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_79.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_61.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_71.setPlaceholderText(_translate("Dialog", "0"))
        self.textEdit_59.setPlaceholderText(_translate("Dialog", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

